# Generated by Django 5.1.1 on 2024-09-24 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildraftsharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagtaildraftsharinglink',
            options={'verbose_name': 'Draftsharing Link', 'verbose_name_plural': 'Draftsharing Links'},
        ),
        migrations.AlterField(
            model_name='wagtaildraftsharinglink',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
